# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DDGStreetImages
                                 A QGIS plugin
 The plugin open DDG street images in the browser
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-08
        copyright            : (C) 2018 by COWI A/S
        email                : jxa@cowi.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DDGStreetImages class from file DDGStreetImages.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ddg_street_images import DDGStreetImages
    return DDGStreetImages(iface)
